#!/usr/bin/env ansible-playbook
---
- hosts: all
  gather_facts: yes
  become: yes

  vars_files:
    - secrets.yml
  vars:
    locale: "en_US.UTF-8"
    timezone: "US/Central"
    packages_to_install:
      - apt-file
      - augeas-tools
      - bpython
      - git
      - htop
      - iotop
      - mlocate
      - mosh
      - pigpio
      - python-pigpio
      - python-rpi.gpio
      - screen
      - silversearcher-ag
      - ssh-askpass
      - tmux
      - vim

    update_cache: no

  tasks:
    - name: put wifi config in place
      template: src=templates/wpa_supplicant.conf.j2 dest=/etc/wpa_supplicant/wpa_supplicant.conf
      notify: reboot
      when: false

    - name: install raspbian packages
      apt: pkg={{ packages_to_install }} state=present update_cache={{ update_cache }}

    - import_tasks: locale.yml

    - import_tasks: dotfiles.yml

    - name: generate ssh keys
      user: name=pi generate_ssh_key=yes
      tags: net, ssh

  handlers:
    - name: reboot
      command: shutdown -r now "Ansible updates triggered"
      async: 0
      poll: 0
      ignore_errors: true

